### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by gchpaco** [gamma-delta/PAUCAL#2]
I experienced a startup crash with paucal 0.4.4 just now on Forge.  Enclosed is the log in question; it didn't get far enough to provide a conventional crash report.
[latest.log](https://github.com/gamma-delta/PAUCAL/files/8793023/latest.log)
.

**Comment by gamma-delta** [comment]
Hey, can you upload that to a service like pastebin or github gist, please?

**Comment by gamma-delta** [comment]
Whoops yeah someone else is having the same issue. I'm working on it ...

**Comment by gamma-delta** [comment]
Ah yeah no wonder, the refmap isn't making it into the jar somehow.

**Comment by gamma-delta** [comment]
Apparently it's a rare but well-known issue with forgegradle no one knows how to fix other than rebuild the jar manually. I've released a version 0.4.5 that should be validated by CF soon; it should be a drop-in replacement for 0.4.4.
