### ISSUE TITLE
issues with scribe's gambit and abacus

### ISSUE THREAD

**Issue by maestro-squiggity** [gamma-delta/PAUCAL#3]
when i pushed 5 nulls and drew scribe's gambit followed by flock's gambit, where scribe's gambit was set to 5, 4 nulls were saved into the list while 1 remained outside the list. this only happened with the number 5 and above, as other numbers below it did not suffer this issue.
![Screenshot (919)](https://user-images.githubusercontent.com/106735705/171599852-e0e6fe1f-e819-49cc-8a5d-a74ed6593e35.png)

**Comment by gamma-delta** [comment]
This is the issue tracker for PAUCAL. Go use the issue tracker for for Hexcasting: https://github.com/gamma-delta/HexMod/issues
